### ISSUE TITLE
What's wrong

### ISSUE THREAD

**Issue by silentmodegroup** [Sanchit43/BOMBitUP#1]
App is showing an update but there is no update in your site! Fix it!

**Comment by Sanchit43** [comment]
@silentmodegroup Please tell me you are on which version??? 

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by silentmodegroup** [comment]
v. 1.9

**Comment by silentmodegroup** [comment]
Also the call bomber is not working. Fix this.

**Comment by Sanchit43** [comment]
@silentmodegroup current latest version is 2.05 you can get it from www.bombitup.tk

Yup working on call bomber 

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by silentmodegroup** [comment]
Still there are bugs in your app. SMS bomber is not working properly, when I'm bombing, the app automatically stops working after sending 4 to 5 messages the app says "unfortunately BOMBITUP has stopped"! Fix it bro!

**Comment by Sanchit43** [comment]
@silentmodegroup Its fixed in the latest version please check 

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by silentmodegroup** [comment]
No bro! I have the latest version 2.05 of your app but still I'm facing the problem.

**Comment by Sanchit43** [comment]
@silentmodegroup Can you please give me a logcat of that error it would be very helpful. 

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Sanchit43** [comment]
@silentmodegroup romreviewer2.0@gmail.com 

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by stephen1401** [comment]
Hey bro what concepts should I know in java to understand this code ?

**Comment by Sanchit43** [comment]
@stephen1401 You should know rest api and java to understand this code. 

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by shyam528** [comment]
Hey it's really well to have fun with friends. Good job (y)

**Comment by Sanchit43** [comment]
@shyam528 thank you 😁

**Comment by rafiqq** [comment]
How to send SMS to number that is already protected....

**Comment by rafiqq** [comment]
I'm still getting prank sms .. my number is protected.. how it's possible

**Comment by Sanchit43** [comment]
@rafiqq there are other bombers too you may be getting bombed from them.

**Comment by rafiqq** [comment]
What are those bombers.. I think I'm getting pranked from bombitup itself

**Comment by Kaushal021** [comment]
I am using the latest version of Bombitup but when I try call blast it says that
' Due to some reason Call api is not working I will push the notification after fixing This'll
Please help me

**Comment by Sanchit43** [comment]
Anonymous sms is fixed will soon fix all bomber

**Comment by Kaushal021** [comment]
Ok sir. Thanks for replying.

**Comment by yatin05** [comment]
There is an issue coming whenever I'm trying to add contacts .
It is saying "something went wrong please try again later "

**Comment by Sanchit43** [comment]
@yatin05 can you please do one thing if you have pc access with net the follow these steps.

1. Open Command Prompt

2. Enter command "ping romreviewer.com" without "

3. Take a screenshot and send it to us we will try to fix it asap.

**Comment by yatin05** [comment]
I didn't understand the 2nd point.
What exactly do I have to type in command prompt ?

Also , I am using this app in my mobile.
How is the PC command thing is gonna help ?

Thank you

**Comment by HrushikeshBodas** [comment]
The app makes a call to an API on API.romreviwer.com to check if the number you entered is in the protection list

**Comment by yatin05** [comment]
Okay , I'll tell you in a hour .

**Comment by yatin05** [comment]
just in case if u didn't get the last mail.

**Comment by Kaushal021** [comment]
Any Solution To Call Bomber?

**Comment by yatin05** [comment]
My app is now working fine .

Thanks a lot.

**Comment by Kaushal021** [comment]
Thank Rom!! Now the app is doing excellent!!! Good Job!!! & Thank's

**Comment by Kaushal021** [comment]
Why have you removed  CALL BLAST?

**Comment by Sanchit43** [comment]
@Kaushal021 Don't worry it will be added back in the next update currently api where dead there was no reason to show it but by the next update new api will be added till then use custom call which is way better than that

**Comment by Kaushal021** [comment]
OK.Please try to update it soon.

**Comment by Kaushal021** [comment]
Please add Call Bomber.And why do you remove it after update?
