### ISSUE TITLE
Removing Of default voice in custom call prank

### ISSUE THREAD

**Issue by Utkarsh2604** [Sanchit43/BOMBitUP#12]
Please Remove the Voice of That Speller lady at the end of custom call prank,and please Update the capacity of Words for custom calls!
PS:- Remove &Update

**Comment by Sanchit43** [comment]
@Utkarsh2604 For now custom call is not working we are trying to fix it first.

**Comment by Utkarsh2604** [comment]
What's The issue

**Comment by Sanchit43** [comment]
@Utkarsh2604  Custom Call Is Dead For Now If We Add it in future we will consider it.
