### ISSUE TITLE
Remove This Repo

### ISSUE THREAD

**Issue by Abhi0725** [Sanchit43/BOMBitUP#4]
Hi Sanchit,

Impressed with your skills. But as a responsible developer I will request you to take this repo down. This repo will cause more harm than good.

Hope you will understand the concern. Thanks.

**Comment by Sanchit43** [comment]
yes i understand  it that's why check out the source code i haven't added any api for bombing. If you compile my code you will not be able to bomb any one.

**Comment by Abhi0725** [comment]
But it does. Many of my colleagues are getting bombarded by someone.

**Comment by c0d3ripp3r** [comment]
Absolutely agree with @abhi0725.. this should be removed with immediate effect.. as of now, your open source code is now available @ Various websites as an APK.

**Comment by Praneeth-Pike** [comment]
There should be a way to identify where you are from. You are causing unnecessary nuisance in people's life. I'm getting messages that are severely effecting my life. 

As a responsible developer, you need to tell us who is pranking us..

**Comment by Sanchit43** [comment]
@Praneeth-Pike for protection we have added protection list to protect from getting message.
If you are still getting them then other sms bomber is being used currently their are thousands of sms bomber google it.
