### ISSUE TITLE
Problem in Anonymous SMS

### ISSUE THREAD

**Issue by GeekyBoyHT** [Sanchit43/BOMBitUP#9]
When i fill out the number and massage and hit send button. A reCaptcha dialog appears and i closes with toast, {not able to connect to recaptcha service(not exact error)}. Please fix it our or tell me the solution.

**Comment by Sanchit43** [comment]
Please try again it won't happen again captcha i notice it is kind of hard but try this for now we will soon switch to another captcha

**Comment by Sanchit43** [comment]
For now anonymous sms is Not available because api is dead but will soon try to fix it and consider removing Captcha
